version: "3.9"

services:
  jupyter_sentinel:
    build:
      context: ./
    image: jupyter_sentinel
    environment:
    - JUPYTER_TOKEN=Sentinel
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/notebooks